services:
  - type: web
    name: domino-boneyard-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements-prod.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DOMINO_ENV
        value: production
      - key: DOMINO_CORS_ORIGINS
        value: "*"
      - key: DOMINO_USE_REDIS
        value: "false" 